create table pictures(product_id serial primary key, img_url text)
INSERT INTO pictures(img_url, product_id)
VALUES('https://s3-us-west-1.amazonaws.com/jtruf72personalproject/tree1.png', 1)
INSERT INTO pictures(img_url, product_id)
VALUES('https://s3-us-west-1.amazonaws.com/jtruf72personalproject/tree2.png', 2)
INSERT INTO pictures(img_url, product_id)
VALUES('https://s3-us-west-1.amazonaws.com/jtruf72personalproject/tree3.png', 3)
INSERT INTO pictures(img_url, product_id)
VALUES('https://s3-us-west-1.amazonaws.com/jtruf72personalproject/tree4.png', 4)
INSERT INTO pictures(img_url, product_id)
VALUES('https://s3-us-west-1.amazonaws.com/jtruf72personalproject/tree5.png', 5)
INSERT INTO pictures(img_url, product_id)
VALUES('https://s3-us-west-1.amazonaws.com/jtruf72personalproject/tree6.png', 6)
INSERT INTO pictures(img_url, product_id)
VALUES('https://s3-us-west-1.amazonaws.com/jtruf72personalproject/tree7.png', 7)
INSERT INTO pictures(img_url, product_id)
VALUES('https://s3-us-west-1.amazonaws.com/jtruf72personalproject/tree8.png', 8)
INSERT INTO pictures(img_url, product_id)
VALUES('https://s3-us-west-1.amazonaws.com/jtruf72personalproject/tree9.png', 9)
INSERT INTO pictures(img_url, product_id)
VALUES('https://s3-us-west-1.amazonaws.com/jtruf72personalproject/tree10.png', 10)
INSERT INTO pictures(img_url, product_id)
VALUES('https://s3-us-west-1.amazonaws.com/jtruf72personalproject/tree11.png', 11)
INSERT INTO pictures(img_url, product_id)
VALUES('https://s3-us-west-1.amazonaws.com/jtruf72personalproject/tree12.png', 12)
INSERT INTO pictures(img_url, product_id)
VALUES('https://s3-us-west-1.amazonaws.com/jtruf72personalproject/tree13.png', 13)
INSERT INTO pictures(img_url, product_id)
VALUES('https://s3-us-west-1.amazonaws.com/jtruf72personalproject/tree14.png', 14)