INSERT INTO products(id, name, price)
VALUES(1, '12 Foot Candy Tree', 400)
INSERT INTO products(id, name, price)
VALUES(2, 'Winter Wonderland', 150)
INSERT INTO products(id, name, price)
VALUES(3, 'Traditional', 150)
INSERT INTO products(id, name, price)
VALUES(4, 'Candy Land', 200)
INSERT INTO products(id, name, price)
VALUES(5, 'The Magic of Christmas', 150)
INSERT INTO products(id, name, price)
VALUES(6, 'Elf Tree', 125)
INSERT INTO products(id, name, price)
VALUES(7, 'Pink Candy', 150)
INSERT INTO products(id, name, price)
VALUES(8, 'Joy to the World', 150)
INSERT INTO products(id, name, price)
VALUES(9, 'Farm House', 150)
INSERT INTO products(id, name, price)
VALUES(10, 'Reindeer', 150)
INSERT INTO products(id, name, price)
VALUES(11, '12 foot Candy Tree 2', 400)
INSERT INTO products(id, name, price)
VALUES(12, 'Merry Christmas', 200)
INSERT INTO products(id, name, price)
VALUES(13, 'Present Tree', 150)
INSERT INTO products(id, name, price)
VALUES(14, 'Peppermint', 165)